In [56]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [57]:
import numpy as np

# printing user defined array and the type,size of array 
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(len(arr))
print('\n')

# printing float values in an numpy array
a = np.zeros(3)
print(a)
b = np.zeros(10)
print(b)

[1 2 3 4 5]
<class 'numpy.ndarray'>
5


[0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [65]:
# different dimensions of an array
# single dimensional array
a = np.array([1,2,3,4])
print(a)

# two dimensional array
b = np.array([[10,20,30],[40,50,60]])
print(b)

# three dimensional array
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(c)
print('\n')

print(a.ndim)
print(b.ndim)
print(c.ndim)
print('\n')

# Indexing through the array created
print(a[2])
print(b[0][2])
print(c[1][0][2])

print('\n')
print(c[0,1,1])
print(b[0,-1])


[1 2 3 4]
[[10 20 30]
 [40 50 60]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


1
2
3


3
30
3


5
30


In [59]:
# Slicing the numpy array
print(arr[0:5])
print(arr[2:4])
print(arr[0::2])
print('\n')

# copy and view the numpy array 
arr = np.array([1,2,3,4,5])
x = arr.copy()
x[0] = 40
print(x)
arr = np.array([1,2,3,4,5])
y = arr.view()
y[2] = 60
print(y)
arr = np.array([1,2,3,4,5,6])

print('\n')

# printing shape of the array
print(arr.shape)

# reshaping the array
newarr = arr.reshape(2,3)
print(newarr)
print(newarr.ndim)

print('\n')
print(arr.reshape(2,3).base)

[1 2 3 4 5]
[3 4]
[1 3 5]


[40  2  3  4  5]
[ 1  2 60  4  5]


(6,)
[[1 2 3]
 [4 5 6]]
2


[1 2 3 4 5 6]


In [63]:
# Iterating through the arrays
# iterating through 1d array
for i in a:
    print(i)

print()

# iterating through 2d array
for i in b:
    for j in i:
        print(j)
print("\n\n")
# iterating through nditer function
for i in np.nditer(b):
    print(i)

1
2
3
4

10
20
30
40
50
60



10
20
30
40
50
60


In [75]:
arr2 = np.array([51,52,53,54])
arr3 = np.array([100,101,102,103])

arr5 = np.concatenate((arr2,arr3))
print(arr5)

arr6 = np.array_split(arr5,3)
print(arr6)

[ 51  52  53  54 100 101 102 103]
[array([51, 52, 53]), array([ 54, 100, 101]), array([102, 103])]
